Automation for an identity provider- IBM blue pages LDAP
ocp-power-automation/ocp4-playbooks-extras pull request #15
Opened 2022-10-10 08:21 UTC by AdityaHonkalas

Signed-off-by: Aditya Honkalas <aditya.honkalas@ibm.com>

2022-10-10 10:14 UTC, yussufsh requested changes

2022-10-10 10:14 UTC, yussufsh commented on playbooks/ibmbluepages-ldap-identity-provider.yml
> +        msg: "Please ensure you have set the environment variable IBM_PASSWORD"
```suggestion
        msg: "Please ensure you have set the environment variable IBM_EMAIL_ID and IBM_PASSWORD"
```

2022-10-10 10:14 UTC, yussufsh commented on playbooks/roles/ibmbluepages-ldap-identity-provider/README.md
> +| ldap_cr_name                 | no       | empty       | User defined name to the LDAP CR object, if undefined default name will be set as name
Default should be `ldapidp`

2022-10-10 10:14 UTC, yussufsh commented on playbooks/roles/ibmbluepages-ldap-identity-provider/README.md
> +| ldap_user_role               | no       | empty       | User role permission to be granted to the newly created user. the possible role permission can be `"admin", "basic-user", "cluster-admin", "c
Default should be `cluster-reader`

2022-11-04 07:24 UTC, yussufsh commented
@pravin-dsilva do we still need this?

2022-11-04 07:56 UTC, pravin-dsilva commented
> @pravin-dsilva do we still need this?

no, we don't. This can be closed.

2022-11-04 07:56 UTC, closed without merging