Implementing rotation of etcd encryption keys
ocp-power-automation/ocp4-playbooks-extras pull request #45
Opened 2023-02-15 06:03 UTC by sajauddin

2023-03-06 06:57 UTC, pravin-dsilva requested changes

2023-03-06 06:57 UTC, pravin-dsilva commented on playbooks/roles/ocp-etcd-rotate-encryption-key/tasks/main.yaml
> +    oc patch openshiftapiserver cluster --type merge -p "
can the kubernetes.core.k8s module be used here

2023-03-06 06:57 UTC, pravin-dsilva commented on playbooks/roles/ocp-etcd-rotate-encryption-key/tasks/main.yaml
> +
remove extra line break

2023-03-06 06:57 UTC, pravin-dsilva commented on playbooks/roles/ocp-etcd-rotate-encryption-key/tasks/main.yaml
> +
remove extra line break

2023-03-06 06:57 UTC, pravin-dsilva commented on playbooks/roles/ocp-etcd-rotate-encryption-key/tasks/main.yaml
> +# check if Cluster Health is good
can reuse https://github.com/ocp-power-automation/ocp4-playbooks-extras/blob/main/playbooks/roles/check-cluster-health/tasks/main.yml

2023-07-13 04:59 UTC, yussufsh commented
@sajauddin could you ptal at the review comments?

2025-04-08 06:47 UTC, closed without merging

2025-04-08 06:48 UTC, sajauddin commented
Addressed in https://github.com/ocp-power-automation/ocp4-playbooks-extras/pull/79