Create playbook for MetalLB installation, validation and e2e tests
ocp-power-automation/ocp4-playbooks-extras pull request #56
Opened 2023-08-25 04:32 UTC by SurajGudaji

Created a variable for namespace, prefixed all variables with metallb_ renamed the e2e test log storing files and removed installation task to avoid duplicacy of resources created by openshift-tests-private.

2023-08-25 06:04 UTC, yussufsh commented
Not sure what is the aim of this PR @SurajGudaji 
We already have metallb operator installation and e2e tests in the upstream. See #53

2023-08-28 06:09 UTC, yussufsh requested changes

2023-08-28 06:09 UTC, yussufsh commented on playbooks/roles/ocp-metallb-operator/README.md
> +| metallb_catalogsource                      | no       | "qe-app-registry"                                                                    | Catalog source channel
```suggestion
| metallb_catalog_source                      | no       | "qe-app-registry"                                                                    | Catalog source channel                                                                                                         |
```

2023-08-28 06:09 UTC, yussufsh commented on examples/all.yaml
>  metallb_golang_tarball: "https://go.dev/dl/go1.18.6.linux-ppc64le.tar.gz"
1.18 is EOL.

2023-08-28 06:09 UTC, yussufsh commented on playbooks/roles/ocp-metallb-operator/README.md
> +| metallb_golang_tarball                     | no       | https://go.dev/dl/go1.18.6.linux-ppc64le.tar.gz                                      | HTTPS URL for golang tarball
The default is not 1.18.

2023-08-28 07:48 UTC, SurajGudaji commented on examples/metallb_vars.yml
> +metallb_namespace: "metallb-system"
Added metallb_namespace variable in README file

2023-08-28 09:09 UTC, yussufsh approved these changes
/lgtm

2023-08-28 09:10 UTC, merged