Automated task for validating rotation of etcd encryption keys
ocp-power-automation/ocp4-playbooks-extras pull request #79
Opened 2024-08-30 07:58 UTC by SurajGudaji

2024-09-05 06:04 UTC, varad-ahirwadkar reviewed
Can we use reuse this role - https://github.com/ocp-power-automation/ocp4-playbooks-extras/tree/main/playbooks/roles/ocp-etcd-encryption-decryption ?

2024-09-05 09:48 UTC, SurajGudaji commented
> Can we use reuse this role - https://github.com/ocp-power-automation/ocp4-playbooks-extras/tree/main/playbooks/roles/ocp-etcd-encryption-decryption ?

we can but this role is defined very statically, so to use it we will need to make some changes to it
i.e calling the the encryption or decryption tasks based on the variables passed by ocp-etcd-rotate-encryption-key role

2024-09-05 09:56 UTC, SurajGudaji commented on playbooks/roles/ocp-etcd-rotate-encryption-key/tasks/main.yaml
> +- name: Execute secret collecter script in etcd pod to collect encrypted value of secrets after key rotation
yes we can

2024-09-27 14:43 UTC, varad-ahirwadkar commented
> we can but this role is defined very statically, so to use it we will need to make some changes to it i.e calling the the encryption or decryption tasks based on the variables passed by ocp-etcd-rotate-encryption-key role

Are you planning to implement these changes?

2024-10-01 10:48 UTC, SurajGudaji commented
> > we can but this role is defined very statically, so to use it we will need to make some changes to it i.e calling the the encryption or decryption tasks based on the variables passed by ocp-etcd-rotate-encryption-key role
> 
> Are you planning to implement these changes?

I was planning to do those changes in next PR because, some more changes related to validation of etcd encryption task were in line, so I will make these changes in next PR

2024-10-22 05:21 UTC, varad-ahirwadkar commented
/approve

2024-10-22 05:22 UTC, varad-ahirwadkar commented
@pravin-dsilva can you please review this PR? Thanks

2024-11-09 14:02 UTC, yussufsh requested changes

2024-11-11 11:14 UTC, yussufsh approved these changes
/lgtm

2024-11-11 11:15 UTC, merged