Hypershift deployment on PowerVS
ocp-power-automation/ocp4-playbooks-extras pull request #8
Opened 2022-09-05 08:52 UTC by pravin-dsilva

Signed-off-by: Pravin D'silva <pravin.dsilva@ibm.com>

2022-09-05 18:21 UTC, Prajyot-Parab commented
/lgtm

/hold-for @yussufsh

2022-11-09 12:45 UTC, varad-ahirwadkar commented on playbooks/roles/hypershift/tasks/main.yml
> +    version:  "{{ hypershift_git_branch }}"
```suggestion
    version: "{{ hypershift_git_branch }}"
```

2022-11-21 05:31 UTC, yussufsh requested changes

2022-11-21 05:31 UTC, yussufsh commented on playbooks/roles/hypershift/defaults/main.yml
> +hypershift_destroy_cluster: false
Shouldn't this be `hypershift_destroy` instead?

2022-11-21 05:31 UTC, yussufsh commented on playbooks/roles/hypershift/defaults/main.yml
> +base_domain: ""
As these are required variables there is no use defining the empty default values which may lead to failures.

2022-11-21 05:31 UTC, yussufsh commented on examples/hypershift_destroy.yaml
> +base_domain: ""
Can we show some example values here? These are required so cannot expect the user to pass an empty string.

2022-11-21 05:31 UTC, yussufsh commented on examples/hypershift_install.yaml
> +ocp_release_image: ""
Please provide an example value.

2022-11-21 05:31 UTC, yussufsh commented on playbooks/roles/hypershift/defaults/main.yml
> +ocp_release_image: ""
Again, the default empty value will fail the create command. Better to remove it from here.

2022-11-21 08:03 UTC, yussufsh approved these changes
/lgtm

2022-11-21 08:05 UTC, merged